contracts/TempusController.sol
contracts/amm/TempusAMM.sol
contracts/amm/interfaces/ITempusAMM.sol
contracts/stats/Stats.sol
test/stats/Stats.test.ts
test/utils/Stats.ts

`getSwapAmountToEndWithEqualShares` just moved to TempusAMM.

Fix estimate exit and redeem

---

.mythx.yml

Unfortunately, the only way to fix this job is to increase min severity, which should be fine.

mythx: Changing min severity

---

package.json

Split from #223, as the remaining file needs more changes.

Include Stats in mythx-misc

---

contracts/utils/mocks/OwnableMock.sol
test/Ownable.test.ts

ownable: Adding tests.

---

contracts/token/vesting/ERC20Vesting.sol
contracts/token/vesting/IERC20Vesting.sol
contracts/utils/Ownable.sol

MIT as most of OZ contracts are MIT as well, and this can be used as a general helper to any project, not really protocol related.

Update license for Ownable and vesting.

---

test/pool-utils/PoolTestFixture.ts

Unfortunately there's no range type in Typescript yet: https://stackoverflow.com/questions/39494689/is-it-possible-to-restrict-number-to-a-certain-range

test: Add assertion that percentage inputs are correct

---

deployments/goerli/StETH.json
deployments/goerli/TempusAMM_Lido staked ETH_maturity_1638190800.json
deployments/goerli/TempusAMM_Lido staked ETH_maturity_1675170000.json
deployments/goerli/TempusPool_Lido staked ETH_maturity1638190800.json
deployments/goerli/TempusPool_Lido staked ETH_maturity1675170000.json
deployments/goerli/Vault.json
hardhat.config.ts
package.json
scripts/deploy.controller.ts
scripts/deploy.pool.lido.ts
scripts/deploy.stats.ts
scripts/utils.ts
scripts/verify.pool.lido.ts
test/utils/TempusPool.ts
yarn.lock

utils: Adding scripts for deployment.

---

contracts/ITempusPool.sol
contracts/TempusPool.sol
contracts/utils/IOwnable.sol
contracts/utils/Ownable.sol

This became more complicated than expected.

pool: Make ITempusFees/TempusPool properly ownable

---

contracts/pools/AaveTempusPool.sol

Somehow this slipped through the review of #239.

pool: Properly submit referrer to Aave

---

contracts/ITempusPool.sol
contracts/TempusPool.sol
test/TempusPool.Deploy.test.ts
test/TempusPool.Redeem.test.ts
test/utils/TempusPool.ts

This is mostly here for a discussion starter.

pool: Exceptionally stop pool in case of a long negative yield period

---

integration-tests/TempusPool.aave.test.ts
integration-tests/TempusPool.compound.test.ts
integration-tests/TempusPool.lido.test.ts
integration-tests/TempusPool.yearn.test.ts
test/TempusPool.Deposit.test.ts
test/TempusPool.Redeem.test.ts
test/pool-utils/PoolTestFixture.ts
test/utils/TempusController.ts

test: Add missing test cases for deposit/redeem to 0 address

---

contracts/TempusController.sol
contracts/pools/LidoTempusPool.sol

The goal is to have the relevant checks grouped in the controller, this is the only outlier.

controller: Move Eth deposit check completely to the controller

---

contracts/TempusController.sol
contracts/TempusPool.sol
test/TempusPool.DepositBackingTokens.test.ts
test/pool-utils/PoolTestFixture.ts

controller: Ensure that untrustedTransferFrom is not called on backingToken(0)

---

contracts/amm/TempusAMM.sol

requires validation of interest rate update order

amm: initial optimization for swaps, using stored interest rate

---

contracts/amm/TempusAMM.sol
test/amm/TempusAMM.test.ts
test/utils/TempusAMM.ts

amm: Add back swapGivenOut method.

---

contracts/ITempusController.sol
contracts/TempusController.sol
contracts/amm/TempusAMM.sol
contracts/amm/interfaces/ITempusAMM.sol
contracts/stats/Stats.sol
test/TempusController.test.ts
test/stats/Stats.test.ts
test/utils/Stats.ts
test/utils/TempusController.ts

controller: Adding leveraged Yield exposure via single transaction

---

contracts/TempusController.sol
test/TempusController.test.ts
test/utils/TempusController.ts

Validate maxLeftoverShares in case of early redeem

---

contracts/TempusController.sol
test/TempusController.test.ts

follow-up for #562 (should have been done there)

bump controller version

---

contracts/ITempusController.sol
contracts/TempusController.sol
test/TempusController.test.ts
test/TempusPool.Deposit.test.ts
test/TempusPool.DepositBackingTokens.test.ts
test/TempusPool.Redeem.test.ts
test/utils/Utils.ts

Introduce custom errors in TempusController

---

contracts/amm/TempusAMM.sol
contracts/amm/math/MockStableMath.sol
contracts/amm/math/StableMath.sol
test/TempusController.test.ts
test/amm/StableMath.test.ts
test/amm/StableMath.ts
test/amm/TempusAMM.test.ts
test/utils/TempusAMM.ts
test/utils/TempusPoolAMM.ts

AMM: rename BPT to LP

---

contracts/ITempusController.sol
contracts/ITempusPool.sol
contracts/TempusController.sol
contracts/TempusPool.sol
contracts/pools/AaveTempusPool.sol
contracts/pools/CompoundTempusPool.sol
contracts/pools/LidoTempusPool.sol
contracts/pools/RariTempusPool.sol
contracts/pools/YearnTempusPool.sol
test/TempusController.test.ts
test/TempusPool.Deploy.test.ts
test/TempusPool.Deposit.test.ts
test/TempusPool.DepositBackingTokens.test.ts
test/TempusPool.Fees.test.ts
test/TempusPool.InterestRate.test.ts
test/TempusPool.Redeem.test.ts
test/TempusPool.RedeemBackingTokens.test.ts
test/TempusPool.YieldShare.test.ts

Introduce custom errors to TempusPool contracts

---

contracts/amm/TempusAMM.sol
contracts/amm/interfaces/ITempusAMM.sol
test/TempusController.test.ts
test/amm/TempusAMM.test.ts

Introduce custom errors to Tempus AMM

---

package.json

Include TempusController, RariTempusPool and YearnTempusPool in mythx-pool

---

contracts/ITempusController.sol

Fixes https://github.com/tempus-finance/tempus-protocol/issues/613

Fixing typo in ITempusController.

---

contracts/amm/ITempusAMM.sol
contracts/amm/TempusAMM.sol
contracts/token/IPoolShare.sol
contracts/token/PoolShare.sol

Fixes https://github.com/tempus-finance/tempus-protocol/issues/470

ERC20Permit support

---

contracts/amm/ITempusAMM.sol
contracts/amm/TempusAMM.sol
test/amm/TempusAMM.test.ts
test/utils/TempusAMM.ts

AMM: Implement swap fee percentage update

---

contracts/ITempusController.sol
contracts/PositionManager.sol
contracts/TempusController.sol
test/TempusController.test.ts

[TempusController] return mintedShares from depositAndFix/depositAndLeverage

---

contracts/PositionManager.sol
contracts/incentivization/ILeverageIncentivization.sol
contracts/incentivization/IStakingRewards.sol
contracts/incentivization/LeverageIncentivization.sol
contracts/incentivization/StakingMath.sol
contracts/incentivization/StakingRewards.sol
contracts/incentivization/StakingRewardsHarness.sol
package.json
test/incentivization/LeverageIncentivization.test.ts
test/incentivization/StakingRewards.test.ts
yarn.lock

Leveraged positions incentivization

---

contracts/ITempusController.sol
contracts/ITempusPool.sol
contracts/TempusController.sol
contracts/TempusPool.sol
test/TempusController.test.ts
test/TempusPool.Deploy.test.ts

https://github.com/tempus-finance/tempus-protocol/pull/617/files#r864567523

Fix ERC165 standart compatibility

---

Writing A Custom Adapter.md

Initial version of the guide. Feel free to update this or comment.

docs: Writing A Custom Adapter for Tempus Protocol

---

tempus-sdk/utils/PermitUtils.ts
tempus-sdk/utils/Utils.ts

test: Use evmMine() helper

---

integration-tests/TempusPool.lido.test.ts
package.json
tempus-sdk/tempus/PoolTestFixture.ts
tempus-sdk/tempus/TempusController.ts

sdk: fix a bug in TempusController.depositBacking

---

integration-tests/TempusPool.compound.test.ts
integration-tests/TempusPool.lido.test.ts
integration-tests/TempusPool.rari.test.ts
scripts/utils.ts
tempus-sdk/utils/Decimal.ts
tempus-sdk/utils/DecimalConvertible.ts
tempus-sdk/utils/DecimalUtils.ts
tempus-sdk/utils/Utils.ts
test/Decimal.test.ts
test/incentivization/LeverageIncentivization.test.ts

This mostly removes BigNumber from all the important places (except AMM StableMath tests)

sdk: decimal remove bignumber

---

contracts/IPositionManager.sol
contracts/PositionManager.sol
package.json
test/PositionManager.test.ts
yarn.lock

emit Burned and Minted events from PositionManager
